#! /bin/bash

    echo -e "\nRpotify is a tool for managing Spotify remotely.\n"
    echo -e "Usage:\n"
    echo -e "    rpotify command [arguments]\n"
    echo -e "Control commands:\n"
    echo "    play"
    echo "    pause"
    echo "    stop"
    echo "    next"
    echo "    prev"
    echo "    up"
    echo "    down"
    echo "    shuffle"
    echo "    repeat"
    echo -e "\nStatus commands:\n"
    echo "    status"
    echo "    now"
    echo "    info"
    echo -e "\nAdvanced commands:\n"
    echo "    uri"
    echo "    search"
    echo -e "\nUse "rpotify help [command]" for more information about a command.\n"