#! /bin/bash

    echo -e "\nRpotify is a tool for managing Spotify remotely.\n"
    echo -e "Usage:\n"
    echo -e "    rpotify command [arguments]\n"
    echo -e "Control commands:\n"
    echo "    play      play/pause music"
    echo "    pause     play/pause music"
    echo "    stop      stop music"
    echo "    next      go to next strack"
    echo "    prev      go to previous track" 
    echo "    up        volume up"
    echo "    down      volume down"
    echo "    shuffle   enable/disable shuffle list mode"
    echo "    repeat    enable/disable repeat list mode"
    echo -e "\nStatus commands:\n"
    echo "    status    show spotify status"
    echo "    now       show track playing now"
    echo "    info      show track information playing now"
    echo -e "\nAdvanced commands:\n"
    echo "    uri       play track/album/list by spotify uri"
    echo "    search    search and play songs/albums/artists"
    echo -e "\nUse "rpotify help [command]" for more information about a command.\n"